services:
  fastapi-app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
    environment:
      - DB_URL=postgres:qwerty1234@pdb:5432/postgres

  postgres-db:
    image: postgres:15-alpine
    hostname: pdb
    environment:
      - POSTGRES_PASSWORD=qwerty1234
    ports:
      - "5433:5432"